spring:
   datasource:
      url: jdbc:mysql://localhost:3306/cm_db
      username: root
      password: password
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
               
   security:
     oauth2:
       client:
         registration:
           facebook:
             clientId: 601758057311517
             clientSecret: bded2cd6cfd9ab5bd1efc9201d73c5cc